![Redis](https://redis.io/wp-content/uploads/2024/04/Logotype.svg?auto=webp&quality=85,75&width=120)

# Laboratório: Busca Vetorial com RedisVL
---

## Introdução 

Neste laboratório, você terá experiência prática usando a biblioteca [RedisVL](https://github.com/redis/redis-vl-python) para realizar busca vetorial em um conjunto de dados JSON de filmes populares.

Como mencionado anteriormente, este laboratório está dividido em cinco seções:

1. Introdução (📍 Você está aqui)
2. Configurar o Redis e importar os dados
3. Vetorizar os dados
4. Realizar técnicas de busca vetorial
5. Conclusão

Você vai desde a configuração do ambiente até o uso de diversas técnicas de busca vetorial. Isso ajudará a construir a base para realizar buscas vetoriais em aplicações de IA do mundo real.

Este laboratório também terá algumas tarefas (indicadas com um 📌) para você praticar com o código. Quando aplicável, as tarefas vêm com um código de solução para comparação.

Além disso, se você quiser visualizar o banco de dados a qualquer momento durante o laboratório, pode voltar à página de documentação do laboratório e abrir o Redis Insight.

Agora que você sabe o que esperar, vamos começar.

## Configurar a conexão com o Redis e importar os dados

Antes de realizar qualquer tipo de busca, precisaremos configurar o Redis e carregar alguns dados (para que possamos pesquisá-los depois). Para este laboratório, usaremos um conjunto de dados de filmes com os seguintes atributos:

- título
- avaliação
- descrição
- gênero

Vamos começar estabelecendo uma conexão com a instância local do Redis, que já está em execução neste notebook.

### Conectar ao Redis

Para começar, precisamos nos conectar ao Redis usando variáveis de ambiente que já foram configuradas para você. Elas incluem o host, a porta e a senha, que usaremos para construir uma URL de conexão para o cliente Redis.

O código abaixo inicializa as variáveis de conexão e cria um objeto `redis_connection`. Verificamos a conexão usando `.ping()`.

Reserve um momento para revisar o código e execute a célula. Se a conexão for bem-sucedida, retornará `True`.

In [18]:
%env REDIS_HOST=memory-canorous-exemplary-77184.db.redis.io
%env REDIS_PORT=13225
%env REDIS_PASSWORD=e0ov1zzjjBFxZeMOK9nyU7CDctQIXV0c
%env REDIS_USER=default

env: REDIS_HOST=memory-canorous-exemplary-77184.db.redis.io
env: REDIS_PORT=13225
env: REDIS_PASSWORD=e0ov1zzjjBFxZeMOK9nyU7CDctQIXV0c
env: REDIS_USER=default

In [19]:
import os
import warnings
from redis import Redis

warnings.filterwarnings('ignore')

REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = os.getenv("REDIS_PORT", "6379")
REDIS_USER = os.getenv("REDIS_USER", "default")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", "")

REDIS_URL = f"redis://{REDIS_USER}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
print(REDIS_URL)
redis_connection = Redis.from_url(REDIS_URL)
redis_connection.ping()

redis://default:e0ov1zzjjBFxZeMOK9nyU7CDctQIXV0c@memory-canorous-exemplary-77184.db.redis.io:13225

True

Agora que a conexão com o Redis está estabelecida, vamos importar os dados dos filmes.

### Importar os dados dos filmes

O conjunto de dados de filmes que usaremos está armazenado em `movies.json`, localizado no diretório `/data`.

Em vez de carregar os dados diretamente no Redis, primeiro os importaremos para um DataFrame do Pandas. Isso nos dá uma cópia local para trabalhar enquanto convertemos os dados em embeddings vetoriais para busca.

Reserve um momento para revisar o código e execute a célula. Se for bem-sucedido, você verá uma tabela de pré-visualização e uma contagem dos filmes carregados.

⚠️ **Nota:** A célula abaixo pode levar algum tempo para ser executada. Por favor, seja paciente enquanto ela é concluída e observe os resultados.

In [21]:
import pandas as pd

df = pd.read_json("data/movies.json")
print("Carregados", len(df), "registros de filmes")

df.head()

Carregados 55 registros de filmes

,id,title,genre,rating,description
0,1,Explosive Pursuit,action,7,A daring cop chases a notorious criminal acros...
1,2,Skyfall,action,8,James Bond returns to track down a dangerous n...
2,3,Fast & Furious 9,action,6,Dom and his crew face off against a high-tech ...
3,4,Black Widow,action,7,Natasha Romanoff confronts her dark past and f...
4,5,John Wick,action,8,A retired hitman seeks vengeance against those...

A seguir, vamos preparar os dados que importamos para a busca vetorial.

## Vetorizar os dados

Nesta seção, vamos vetorizar os dados. Primeiro, pegaremos o campo de descrição de cada documento JSON e o transformaremos em um embedding vetorial. Armazenaremos esse embedding como uma propriedade adicional no documento, junto com seus outros campos. Em seguida, criaremos um índice de busca Redis que inclui todos os campos do documento (incluindo o embedding). Na prática, você só precisa indexar os campos que serão consultados. Neste caso, isso acaba sendo todos eles.

Primeiro, transformaremos nossos dados JSON brutos em embeddings vetoriais e, em seguida, pegaremos esses embeddings e os indexaremos no Redis, tornando-os pesquisáveis.

No final, teremos passado de dados brutos para um conjunto de dados totalmente indexado e pesquisável — pronto para busca vetorial.

### Uma breve recapitulação sobre embeddings vetoriais

Vamos revisitar um conceito central por trás da maioria das aplicações baseadas em LLM: os embeddings vetoriais.

Embeddings são vetores de alta dimensão — como `[0.1316, 0.7251, 0.4055, ...]` — que representam o conteúdo semântico do texto em um formato que os modelos de aprendizado de máquina podem processar. Isso nos permite comparar textos com base na similaridade contextual, mesmo quando eles não compartilham as mesmas palavras.

Você usará o RedisVL para gerar e armazenar embeddings para que possamos pesquisar nosso conjunto de dados por relevância semântica — não apenas por palavras-chave.

### Criando embeddings usando o RedisVL

A biblioteca RedisVL fornece métodos úteis para criar e gerenciar embeddings vetoriais, facilitando sua integração em fluxos de trabalho de IA. Abaixo, veremos como incorporar uma lista de descrições de filmes usando um modelo transformer e armazenar os resultados em um DataFrame para indexação posterior.

Há duas classes principais que usaremos do RedisVL:

1. `HFTextVectorizer`: É um wrapper em torno dos modelos transformer da Hugging Face que facilita a geração de embeddings vetoriais.

2. `EmbeddingsCache`: Esta classe ajuda a armazenar e reutilizar embeddings usando o Redis como cache.

Reserve um momento para revisar o código e execute a célula. Os argumentos fornecidos são autoexplicativos, mas opcionalmente, você pode explorar uma análise mais detalhada no menu suspenso abaixo.

⚠️ **Nota:** A célula abaixo pode levar algum tempo para ser executada. Por favor, seja paciente enquanto ela é concluída e observe os resultados.

In [24]:
from redisvl.utils.vectorize import HFTextVectorizer
from redisvl.extensions.cache.embeddings import EmbeddingsCache

os.environ["TOKENIZERS_PARALLELISM"] = "false"


hf = HFTextVectorizer(
    model="sentence-transformers/all-MiniLM-L6-v2",
    cache=EmbeddingsCache(
        name="embedcache",
        ttl=600,
        redis_client=redis_connection,
    )
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2547.64it/s]

<details>
<summary> (Opcional) O que faz a configuração <code>"TOKENIZERS_PARALLELISM"</code>? </summary>
<br>
Esta configuração é usada para limpar a saída que recebemos. Ela suprime um aviso da biblioteca Hugging Face transformers relacionado ao paralelismo do tokenizer. Por padrão, os tokenizers podem tentar usar múltiplas threads, o que pode causar avisos ou sobrecarga desnecessária em um ambiente de notebook.
</details>

<details>
<summary> (Opcional) Detalhamento dos parâmetros do HFTextVectorizer </summary>
<br>
Para <code>HFTextVectorizer</code> fornecemos dois argumentos:

- model: O nome de um modelo sentence transformer da Hugging Face. No nosso caso, usaremos "sentence-transformers/all-MiniLM-L6-v2", um modelo rápido e leve, ideal para busca semântica.

- cache: Um argumento opcional que atribui uma instância de `EmbeddingsCache` que ajuda a evitar recomputar embeddings para entradas repetidas.

Para <code>EmbeddingsCache</code> fornecemos três argumentos:

- name: Um prefixo de chave para usar no Redis para o cache

- ttl: Um argumento opcional que define por quanto tempo os embeddings em cache devem viver no Redis (em segundos)

- redis_client: O cliente Redis usado para armazenar e recuperar vetores.

Uma lista mais detalhada de todos os parâmetros pode ser encontrada na documentação do RedisVL para [HFTextVectorizer](https://docs.redisvl.com/en/latest/api/vectorizer.html#hftextvectorizer) e [EmbeddingsCache](https://docs.redisvl.com/en/latest/api/cache.html#embeddingscache).

</details>

Agora, vamos usar o vetorizador no conjunto de dados de filmes. Revise o código abaixo, execute-o e observe os resultados.

In [25]:
df["vector"] = hf.embed_many(df["description"].tolist(), as_buffer=True)

O código acima pegou a coluna de descrição do DataFrame, passou o texto para o método `embed_many()` e gerou embeddings vetoriais em lote, armazenando os vetores resultantes — codificados como buffers binários compactos (especificado por `as_buffer=True`) — em uma nova coluna (no mesmo DataFrame) chamada "vector".

<details>
<summary>(Opcional) O que é um buffer binário compacto?</summary>
<br>
Um buffer binário compacto é uma forma eficiente em termos de espaço para armazenar dados. Neste caso, os embeddings vetoriais são armazenados como bytes brutos em vez de uma lista de números de ponto flutuante (por exemplo, <code> b'\x00\x00\x80?\x9a\x99\x19@...'</code> em vez de <code>[1.0, 6.4, ...]</code>).

O buffer usa o argumento `dtype` especificado no vetorizador, que por padrão é "float32". Como queríamos manter o padrão, não precisamos defini-lo explicitamente em nossa chamada acima.

</details>

Visualize a nova coluna executando a seguinte célula:

In [26]:
df.head()

,id,title,genre,rating,description,vector
0,1,Explosive Pursuit,action,7,A daring cop chases a notorious criminal acros...,b'\xa4f|=\xcfa\n;\xee\x91\xb7;\x1c\xcb~\xbdJe\...
1,2,Skyfall,action,8,James Bond returns to track down a dangerous n...,b'\x9dD\x9e\xbd;\x9b\x89\xbc\xcf\x16\x95\xbc\x...
2,3,Fast & Furious 9,action,6,Dom and his crew face off against a high-tech ...,b' \xa5\xc7\xbc\x00-\xa2=7\x19H\xbcL\xc6t\xbd\...
3,4,Black Widow,action,7,Natasha Romanoff confronts her dark past and f...,b't\xeb\x85\xbd\x00\xcdo\xbdx\xe8\xc2\xbbF\xcf...
4,5,John Wick,action,8,A retired hitman seeks vengeance against those...,b'\x9f<x\xbb\x04/\xc5=F\x86:;\xb8\xd0\x94<\xa4...

Agora que temos nossos embeddings vetoriais, vamos criar um índice e um esquema para habilitar a capacidade de pesquisá-los.

### Visão geral da criação do esquema

No Redis core, a definição de um esquema e a criação de um índice são realizadas juntas usando o comando [`FT.CREATE`](https://redis.io/docs/latest/commands/ft.create/). Por exemplo, se estivéssemos trabalhando com um conjunto de dados para uma base de conhecimento empresarial, poderíamos executar o seguinte comando:

```bash
FT.CREATE knowledge-base
ON JSON 
    PREFIX 1 kb:
SCHEMA
    "$.author" AS "author" TEXT NOSTEM WEIGHT 1.0
    "$.department" AS "department" TAG 
```

No RedisVL, o mesmo comando `FT.CREATE` subjacente é executado nos bastidores, mas o processo é dividido em duas etapas separadas:
1. Definir o esquema
2. Criar o índice com base nesse esquema

Começaremos esta seção primeiro definindo o esquema.

O esquema pode ser criado usando a classe [`IndexSchema`](https://docs.redisvl.com/en/latest/api/schema.html#indexschema), que permite definir o esquema a partir de um arquivo YAML ou de um dicionário Python. Neste laboratório, definiremos um usando um dicionário através do método `.from_dict()`.

O esquema tem duas partes principais que devem ser definidas:

1. Uma seção de índice, que configura configurações específicas do índice, como nome do índice, prefixo da chave e se os documentos são armazenados como Hashes ou JSON.

2. Uma lista de campos, que define quais campos devem ser indexados e como devem ser pesquisados. Cada campo tem um nome, um tipo (por exemplo, texto, tag, numérico ou vetor) e quaisquer atributos obrigatórios/opcionais. Uma lista completa dos tipos de campo e atributos suportados pode ser encontrada na [documentação do RedisVL](https://docs.redisvl.com/en/latest/api/schema.html#supported-field-types-and-attributes).

Você construirá o esquema completo para os dados dos filmes em breve, mas para se familiarizar com a sintaxe, examine o exemplo parcial abaixo antes de prosseguir.

```python 

schema = IndexSchema.from_dict({
  "index": {
    "name": "movies",
    "prefix": "...",
    "storage_type": "..."
  },
  "fields": [
    {
        "name": "title",
        "type": "text",
        "attrs": {
          ...
        }
    },
    {
      ...
    }
  ]
})

```

### Definir o Esquema do Índice

É hora de criar o esquema. Complete a tarefa abaixo.

📌 **Tarefa 1: Criar o esquema**

Fornecemos o código inicial para o esquema dos dados dos filmes. Sua tarefa é completá-lo usando as definições de campo listadas abaixo.

Crie um esquema chamado `"movies"` com:
- Um prefixo de `"movies"`
- Um tipo de armazenamento de `"hash"`

Inclua os seguintes campos:

| Nome do Campo | Tipo      | Atributos                                                                   |
|---------------|-----------|-----------------------------------------------------------------------------|
| `title`       | `text`    | _nenhum_                                                                    |
| `description` | `text`    | _nenhum_                                                                    |
| `genre`       | `tag`     | `sortable: True`                                                            |
| `rating`      | `numeric` | `sortable: True`                                                            |
| `vector`      | `vector`  | `dims: 384`  <br> `distance_metric: "cosine"` <br> `algorithm: "flat"` <br> `datatype: "float32"` |


Lembre-se de executar a célula assim que o esquema estiver completo. O código da solução está publicado abaixo se você precisar de ajuda ou quiser comparar sua resposta.

In [ ]:
from redisvl.schema import IndexSchema

index_name = "movies"

schema = IndexSchema.from_dict({
    "index": {
        # Preencha o nome, prefixo e storage_type

    },
    "fields": [
        # Adicione os campos obrigatórios abaixo

    ]
})

print('Esquema criado:', schema)

<details>
<summary> 🔒 Código da Solução do Esquema </summary>
<br>

```python

from redisvl.schema import IndexSchema

index_name = "movies"

schema = IndexSchema.from_dict({
    "index": {
        "name": "movies",
        "prefix": "movies",
        "storage_type": "hash"
    },
    "fields": [
        {
            "name": "title",
            "type": "text"
        },
        {
            "name": "description",
            "type": "text"
        },
        {
            "name": "genre",
            "type": "tag",
            "attrs": {
                "sortable": True
            }
        },
        {
            "name": "rating",
            "type": "numeric",
            "attrs": {
                "sortable": True
            }
        },
        {
            "name": "vector",
            "type": "vector",
            "attrs": {
                "dims": 384,
                "distance_metric": "cosine",
                "algorithm": "flat",
                "datatype": "float32"
            }
        }
    ]
})

print('Esquema criado:', schema)

```

</details>

### Adicionar um índice

Junto com o esquema, precisamos criar o índice. Para isso, podemos usar a classe [`SearchIndex`](https://docs.redisvl.com/en/latest/api/searchindex.html#searchindex-api), que tem um método `.create()`. A classe recebe dois argumentos obrigatórios:

- `schema`: O esquema do índice que você deseja usar.

- `client`: Uma instância do cliente Redis.

Execute a célula abaixo. **Não haverá saída, pois estamos criando o índice, mas o observaremos no próximo passo.**

In [ ]:
from redisvl.index import SearchIndex

index = SearchIndex(schema, redis_connection)
index.create(overwrite=True, drop=True)

       
> **🚨 Cuidado Extremo:** É importante estar ciente ao usar o método `.create()`, `overwrite=True` sobrescreve um índice no Redis
> sem excluir os dados associados. No entanto, definir `drop=True` excluirá tanto o índice QUANTO **todos os documentos associados** (tudo limpo). `drop=True` só terá efeito quando `overwrite=True` também estiver definido.
> 
> Tenha muito cuidado ao definir isso, pois um erro pode causar perda de dados.

Podemos usar [`rvl`](https://docs.redisvl.com/en/latest/overview/cli.html), a CLI integrada ao RedisVL, para confirmar que o índice foi criado. Execute o código abaixo para visualizar e confirmar que o índice de filmes foi criado.

In [ ]:
!rvl index info -i movies -u {REDIS_URL}

### Popular o índice

Agora, podemos carregar nossos dados no Redis usando o método `.load()`. Este método tem um argumento obrigatório (e vários opcionais) chamado `data` que recebe um iterável para carregar (como as linhas do nosso DataFrame). Quando chamado, ele escreverá cada registro no Redis, e construirá chaves usando o prefixo do índice, garantindo que os dados sejam indexados automaticamente de acordo com o esquema.

Execute a seguinte célula para carregar os registros:

In [ ]:
index.load(df.to_dict(orient="records"))

<details>
<summary>(Opcional) O que faz <code>orient="records"</code>? </summary>
<br>
A propriedade orient determina o tipo dos valores do dicionário. Passar <code>"records"</code> como valor para a propriedade orient faz com que os dados tenham a seguinte estrutura:

  - Cada dicionário representa uma linha (ou documento)
  - As chaves são os nomes das colunas e os valores são os valores das células correspondentes

Por exemplo:

```python

[ 
  {"title": "Procurando Nemo", "genre": "Animação", "rating": 8.1, "vector": [...]},
  ...
]

```

A lista completa de valores aceitáveis para a propriedade orient pode ser encontrada na <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_dict.html#pandas.DataFrame.to_dict">documentação do Pandas DataFrame.</a>
</details>

📌 **Tarefa 2: Confirmar os dados**  

Confirme os dados buscando um dos filmes no banco de dados. Pegue qualquer uma das chaves que foram carregadas acima (por exemplo, `'movies:01K0791...'`) e insira-a no código abaixo. Em seguida, execute-o para confirmar que ele é retornado e tem um campo vetorial. Alternativamente, os dados podem ser visualizados no Redis Insight.

In [ ]:
# Ex. redis_connection.hgetall("movies:01K07...")

redis_connection.hgetall("PREENCHA A CHAVE AQUI")

Com isso concluído, armazenamos e indexamos com sucesso os dados no Redis. Agora estamos prontos para explorar como pesquisá-los.

## Técnicas de busca

Nesta seção, realizaremos uma variedade de técnicas de busca nos dados que carregamos. Isso inclui:

- Busca KNN (K-Nearest Neighbors)
- Busca vetorial com filtros
- Consultas de intervalo
- Busca híbrida

### Busca KNN

Vamos começar com a forma mais básica de busca vetorial que implementa o algoritmo K-Nearest Neighbors (KNN). Este tipo de busca encontra os itens em um conjunto de dados que estão mais próximos em significado a uma determinada consulta, mesmo que nem todos sejam relevantes.

Primeiro, precisamos incorporar uma consulta específica do usuário. Por enquanto, vamos codificar isso e usar `"Filme de alta tecnologia e cheio de ação"`. Podemos usar o vetorizador que criamos anteriormente (`hf`) e chamar o método `.embed()` (antes usamos o `.embed_many()`).

Execute a seguinte célula:

In [ ]:
user_query = "Filme de alta tecnologia e cheio de ação"

embedded_user_query = hf.embed(user_query)

Agora, podemos realizar a busca propriamente dita. Para isso, podemos usar a classe [`VectorQuery`](https://docs.redisvl.com/en/latest/api/query.html#) do RedisVL. Abaixo, definimos uma consulta que obterá as três correspondências mais próximas e retornará os campos `"title"` e `"genre"`.

Execute a célula e observe a string de consulta que ela retorna.

In [ ]:
from redisvl.query import VectorQuery

vec_query = VectorQuery(
    vector=embedded_user_query,
    vector_field_name="vector",
    num_results=3,
    return_fields=["title", "genre"],
    return_score=True,
)

print("Consulta vetorial:", vec_query)

<details>
<summary> (Opcional) Detalhamento dos parâmetros do VectorQuery </summary>
<br>

Acima, definimos o VectorQuery com os seguintes parâmetros:

- vector: A versão incorporada da consulta do usuário (geramos isso na etapa anterior e armazenamos na variável `embedded_user_query`).

- vector_field_name: O nome do campo vetorial no índice (usamos `"vector"` no esquema).

- num_results: O número de correspondências mais próximas a retornar — este é o "K" no KNN.

- return_fields: Um argumento opcional que lista os campos do documento a serem retornados do Redis (por exemplo, "title", "genre"). Por padrão, retornará todos os campos.

- return_score: Um argumento opcional que inclui a pontuação de similaridade para cada resultado (quanto menor, mais similar). O padrão é `False` se não definido e não retornará a pontuação.

A lista completa de parâmetros disponíveis pode ser encontrada na [documentação da API VectorQuery do RedisVL](https://docs.redisvl.com/en/latest/api/query.html#vectorquery).
</details>

Observe que o `vec_query` resultante é uma expressão de consulta Redis de baixo nível. Isso ocorre porque, na próxima etapa, o RedisVL usará o comando `FT.SEARCH` nos bastidores para executá-lo.

Agora que construímos o objeto de consulta, podemos passá-lo para `index.query()` para realizar a busca. Envolver os resultados com `pd.DataFrame()` formatará o resultado como uma tabela legível. Execute o código abaixo para vê-lo em ação!

In [ ]:
result = index.query(vec_query)
pd.DataFrame(result)

Podemos ver que a consulta está retornando alguns resultados para filmes "de alta tecnologia e cheios de ação".

📌 **Tarefa 3: Experimente com a consulta**  

Reserve um momento para alterar a consulta do usuário na célula acima e execute novamente a busca. Aqui estão algumas sugestões para tentar:

- História animada saudável sobre amizade
- Quero algo que pareça com a Pixar

⚠️ **Nota:** Após alterar a consulta, você precisará executar novamente as três células mais recentes acima para que a nova consulta seja executada.

Quando terminar, passe para a próxima técnica de busca.

### Busca vetorial com filtros

O Redis permite combinar buscas com filtros nos campos do objeto de índice, o que ajuda a criar buscas mais específicas. Há uma variedade de [filtros](https://docs.redisvl.com/en/latest/api/filter.html#) para campos de texto, número, tag e geo.

Por exemplo, digamos que queremos buscar os três melhores filmes especificamente no gênero "ação". Como o campo é uma tag (especificamos como tag no esquema do índice), podemos usar a classe `Tag` combinada com o método `.set_filter()` para filtrar por seu valor.

Observe que o método `.set_filter()` é uma maneira rápida de definir a expressão de filtro da consulta vetorial que definimos anteriormente sem reescrevê-la.

Execute a célula abaixo para estabelecer e consultar pela tag. Supondo que a consulta ainda seja `"Filme de alta tecnologia e cheio de ação"`, o resultado deve conter apenas os filmes que são do gênero "ação". Se você alterou a consulta na célula anterior, o resultado será diferente.

In [ ]:
from redisvl.query.filter import Tag

tag_filter = Tag("genre") == "action"

vec_query.set_filter(tag_filter)

result=index.query(vec_query)
pd.DataFrame(result)

📌 **Tarefa 4: Experimente com a consulta**  

Reserve um momento para alterar o gênero para "comédia" e execute novamente a célula acima para observar a diferença.

Quando terminar, passe para a próxima técnica de busca.

### Busca vetorial com filtro de texto

Outro exemplo de filtro comum é o filtro de texto. Por exemplo, digamos que queremos buscar filmes que mencionem diretamente "gênio do crime" na descrição. Podemos fazer isso usando a classe `Text`.

Veja a implementação abaixo e execute o código para ver o resultado.

In [ ]:
from redisvl.query.filter import Text

text_filter = Text("description") % "gênio do crime"

vec_query = VectorQuery(
    vector=embedded_user_query,
    vector_field_name="vector",
    num_results=3,
    return_fields=["title", "rating", "genre", "description"],
    return_score=True,
    filter_expression=text_filter
)

result = index.query(vec_query)
pd.DataFrame(result)

Observe que acima, definimos o `filter_expression` diretamente quando criamos `vec_query` novamente. Esta é uma alternativa ao uso do método `.set_filter()`.

📌 **Tarefa 5: Experimente com a consulta**  

Reserve um momento para alterar o text_filter para "família" e execute novamente a célula acima para observar a diferença.

Quando terminar, passe para a próxima técnica de busca.

### Múltiplos filtros

Além de usar filtros individuais, também podemos filtrar com uma combinação de filtros. Isso não pode ser feito chamando `.set_filter()` várias vezes, porque ele não mescla filtros; em vez disso, sobrescreve qualquer expressão de filtro anterior.

Em vez disso, o filtro combinado precisa ser criado antecipadamente usando operadores lógicos como `&` (E) ou `|` (OU), e então passado uma vez para `.set_filter()` ou para a consulta quando ela é definida.

Por exemplo, digamos que queríamos fazer tanto o filtro de tag acima quanto um filtro para filmes com avaliação de 7 ou superior. Examine e execute a seguinte célula:

In [ ]:
from redisvl.query.filter import Num

num_filter = Num("rating") >= 7
tag_filter = Tag("genre") == "action"

combined_filter = tag_filter & num_filter

# reconstruir a consulta vetorial
vec_query = VectorQuery(
    vector=embedded_user_query,
    vector_field_name="vector",
    num_results=3,
    return_fields=["title", "rating", "genre"],
    return_score=True,
    filter_expression=combined_filter
)

result = index.query(vec_query)
pd.DataFrame(result)

No código acima, estamos usando um novo filtro para valores numéricos ("rating") com o método `Num` fornecido pelo RedisVL. Em seguida, combinamos os filtros usando a sintaxe `&` e os passamos para a consulta vetorial. Isso nos permitirá filtrar filmes que são do gênero "ação", mas também têm uma avaliação de 7 ou superior.

O RedisVL oferece uma variedade de outras formas de buscar texto, como correspondência com curingas e correspondência difusa. Todos esses exemplos e mais podem ser encontrados na [documentação do RedisVL sobre filtros de texto](https://docs.redisvl.com/en/latest/user_guide/02_hybrid_queries.html#text-filters).

📌 **Tarefa 6: Experimente com a consulta**  

Reserve um momento para alterar os filtros de gênero e avaliação. Recomendamos buscar filmes de "comédia" com avaliação de 8 ou superior. Execute novamente a célula acima para observar a diferença.

Quando terminar, passe para a próxima técnica de busca.

### Consultas de intervalo

Até agora, usamos a busca K-Nearest Neighbors (KNN), que sempre retorna os N melhores resultados, mesmo que alguns não sejam muito semelhantes. As consultas de intervalo nos dão mais controle, permitindo definir um limite para o que é considerado "semelhante o suficiente".

Em vez de perguntar: "Quais são os 5 documentos mais próximos?" uma consulta de intervalo nos permite dizer: "Retorne apenas documentos dentro de uma determinada distância."

Isso é útil quando você se importa mais com a qualidade do que com a quantidade e não quer incluir resultados pouco relacionados. Essa distância é definida através de um parâmetro `distance_threshold` definido em uma instância da classe `RangeQuery`.

Examine e execute a consulta de intervalo definida na célula abaixo.

In [ ]:
from redisvl.query import RangeQuery

user_query = "Filmes de fantasia amigáveis para a família"

embedded_user_query = hf.embed(user_query)

range_query = RangeQuery(
    vector=embedded_user_query,
    vector_field_name="vector",
    return_fields=["title", "rating", "genre"],
    return_score=True,
    distance_threshold=0.8  # encontrar todos os itens com distância semântica menor que 0.8
)

result = index.query(range_query)
pd.DataFrame(result)

<details>
<summary> (Opcional) Como funciona o limite de distância? </summary>
<br>

A distância é interpretada usando o valor definido para `"distance_metric"` via esquema do índice. No nosso, definimos como `"cosine"`.

A distância cosseno está no intervalo de 0 a 2, que pode ser normalizada (para ficar entre 0 e 1) se você definir um parâmetro opcional `normalize_vector_distance` como `True`. A função cosseno não é linear, mas como uma estimativa rápida, um valor de `0.8` é aproximadamente 80% de erro (ou seja, qualquer coisa mais próxima que 80% da distância máxima possível).

</details>

📌 **Tarefa 7: Experimente com a consulta**  

Tente diminuir o limite para 0.73 para tornar o filtro mais restrito e observe os resultados.


### Busca híbrida

Até agora, exploramos a busca vetorial, que combina com base no significado, e sabemos que o Redis também suporta busca por texto (tanto através de um filtro quanto de uma classe [TextQuery](https://docs.redisvl.com/en/latest/api/query.html#textquery) separada para consultas apenas de texto, que não invocam similaridade vetorial). No entanto, e se quisermos o melhor dos dois mundos? É aí que entra a busca híbrida.

A busca híbrida permite combinar busca em texto completo com similaridade vetorial para melhorar a relevância e a precisão.

Por exemplo, uma consulta híbrida para "filmes sobre inteligência artificial" pode retornar:

- Uma correspondência lexical: "Artificial Intelligence: AI" (correspondência direta de palavra-chave)
- Uma correspondência semântica: "Ex Machina" ou "Her" — filmes que não usam a frase exata, mas são sobre o tópico solicitado.

Com a busca híbrida, ambos os tipos de resultados aparecem — classificados por quão bem correspondem à sua intenção e palavras-chave.

A boa notícia é que o RedisVL tem uma classe `HybridQuery` integrada para ajudar a executar esses tipos de consultas. Ela recebe tanto uma entrada de texto quanto um vetor de consulta, e o Redis retornará resultados que refletem ambos os sinais.

Veja o exemplo de consulta híbrida abaixo, execute a célula para estabelecer o objeto de consulta e observe a consulta que ela cria.

In [ ]:
from redisvl.query import HybridQuery

hybrid_query = HybridQuery(
    text=user_query,
    text_field_name="description",
    text_scorer="BM25",
    vector=embedded_user_query,
    vector_field_name="vector",
    alpha=0.7,
    num_results=20,
    return_fields=["title", "description"],
)

print("Objeto de consulta híbrida:", hybrid_query)

Vamos detalhar os novos argumentos introduzidos aqui:

- `text`: Esta é a palavra-chave ou frase bruta para usar na busca em texto completo. Será pontuada usando BM25. Simplesmente usaremos a consulta que definimos anteriormente para "Filmes de fantasia amigáveis para a família" (ou o que quer que a consulta tenha sido alterada quando você estava experimentando).

- `text_field_name`: O nome do campo em seus documentos para aplicar a busca em texto completo — no nosso caso, "description".

- `text_scorer`: Define como a pontuação do texto completo é calculada. Você deve inserir um dos métodos suportados pela documentação do RedisVL (BM25 ou TFIDF). O usado neste exemplo, BM25, é o algoritmo de classificação padrão usado em mecanismos de busca.

- `alpha`: Diz ao mecanismo de busca quanto peso dar à similaridade vetorial versus a similaridade de texto. Os documentos serão pontuados como: `hybrid_score = (alpha) * vector_score + (1-alpha) * text_score`. Valores maiores de alpha favorecem a similaridade semântica, enquanto valores menores favorecem a correspondência de palavras-chave.

Todo o resto funciona da mesma forma que o `VectorQuery`.

Agora, vamos executar a consulta híbrida abaixo e ver os resultados. Deve retornar os 4 principais documentos correspondentes e mostrar como cada um foi pontuado em:

- similaridade vetorial (a pontuação do vetor)
- pontuação de texto
- pontuação híbrida final (uma combinação ponderada)

In [ ]:
result = index.query(hybrid_query)[:4]
pd.DataFrame(result)[["title", "vector_similarity", "text_score", "hybrid_score"]]

## Conclusão 🏁 

Ótimo trabalho! Você concluiu o laboratório sobre busca vetorial com RedisVL.

Neste laboratório, você aprendeu como:

- Conectar-se a uma instância do Redis e usar o Pandas para ler e analisar um documento JSON
- Usar o RedisVL para gerar embeddings vetoriais para dados JSON
- Definir e criar um esquema e índice Redis
- Indexar dados no Redis
- Realizar uma variedade de técnicas de busca, incluindo:
    - Busca vetorial K-Nearest Neighbors (KNN)
    - Busca vetorial com filtros de tag, texto e numéricos
    - Consultas de intervalo com limites de distância
    - Busca híbrida combinando texto completo e similaridade vetorial

Estas são as habilidades fundamentais para construir sistemas de busca semântica. Sinta-se à vontade para experimentar mais com as consultas e filtros, ou revisitar qualquer seção para praticar.

Para concluir o curso e obter seu certificado, volte ao [curso da Redis University](https://flockjay.com/course/1npvvtfft2agew/submodule/muke9uj9pwmk4n/) e complete a verificação de conhecimento.

Após concluir este curso, encorajamos você a fazer nosso curso [Construa um Chatbot RAG](https://flockjay.com/course/ihjs7iip0gpkrw), onde você desenvolverá suas habilidades com RedisVL e construirá um assistente de IA totalmente funcional e pronto para produção que usa Redis para busca vetorial, cache semântico e memória conversacional.

Além disso, confira qualquer um dos nossos recursos de IA:
- [Redis University](https://university.redis.io/): Torne-se um especialista em Redis em nossa plataforma universitária
- [Recursos de IA da Redis](https://github.com/redis-developer/redis-ai-resources): Um repositório curado de recursos para casos de uso básicos e avançados de Redis no ecossistema de IA.
- [Documentação Redis para IA](https://redis.io/docs/latest/develop/ai/): Uma visão geral da documentação do Redis para IA e busca
- [RedisVL](https://github.com/redis/redis-vl-python): O repositório GitHub do RedisVL